# Build a container via the command "make build"
# By Jason Gegere <jason@htmlgraphic.com>

all:: build


build:
	docker build --rm -t htmlgraphic/base:16.04 .
push:
	docker push htmlgraphic/base:16.04
